### ISSUE TITLE
Shotguns reduced to 1 projectile upon loading character

### ISSUE THREAD

**Issue by mouseas** [wizzomafizzo/starcheat#191] opened 2015-05-24 07:55 UTC
Whenever I open a character, all shotguns and plasma shotguns on their person go from have about 5 projectiles per shot to 1 per shot. If I open a character, change nothing, and save, all my shotguns are nerfed.

**Comment by wizzomafizzo** [comment] 2015-05-25 01:33
Hi. Is it possible to get an example JSON output of the before and after of one of these items?

**Comment by mouseas** [comment] 2015-05-25 03:13
https://www.dropbox.com/sh/5h3ozvll7dctcki/AADC_83a7QTWh3f2x4innBW6a?dl=0

.player_mybak is the original version. The .player is the edited version. All I did was open the character and then save it. The shotgun is in the first hotbar slot.

**Comment by wizzomafizzo** [comment] 2015-05-25 03:30
wicked. thanks man, much appreciated. i will try and get a hotfix out soon after this is fixed plus an issue with showing player armour

**Comment by wizzomafizzo** [comment] 2015-05-25 07:06
i'll keep trying but i'm having trouble reproducing this. your example player (the original one, not the nerfed one) seems to have all the items already set to 1 projectile and if i change that to a higher number, save and restart it it doesn't get changed. am i looking at the right item key? projectileCount?

like i said i'll keep screwing around with it but it's such a strange issue, starcheat shouldn't be making any changes to item slots unless specifically told to and has no concept of the difference between shotguns and any other generated gun

**Comment by mouseas** [comment] 2015-05-25 17:24
I think it is having issues with projectileCount, I think shotguns are just the only guns with a value >1. If I change a gun to have multiple projectiles, it always ends up back at 1, and spread gets reset to 0.

**Comment by Flipdecoin** [comment] 2015-05-26 19:52
I've also experienced this tick. I still haven't found a stable fix for it through Starcheat. I think its between projectileCount and Spread, but I don't really know how to prove that. I have noticed that, like mouseas said, sometimes when loading up a game, it will screw with the shotguns. I've spawned in a randomgenerated shotgun before, and it works fine, then when I go into Starcheat and change Spread from 7 to 8, or projectileCount from 6 to 5, it reverts back to 1 bullet spraying anywhere in the shotgun arc. I'm not sure, but I feel its shooting all the bullets, just in the same....instance? Spot?

**Comment by wizzomafizzo** [comment] 2015-05-27 02:42
Thanks for the info, every little bit helps. I've been pretty busy lately but I'll make sure this is ready for a hotfix release soon enough. It might be worth just going over gun generation in itself, I haven't made more than minor changes since last year.

**Comment by wizzomafizzo** [comment] 2015-05-28 13:47
hi. can you  guys please check out this related issue #177 
specifically the 4th and 5th comments from the bottom by xirukai, he came up with some info ages ago on how the keys might work now since the update

the thing that i need to confirm with you is whether starbound is doing the nerfing or starcheat, because by design starcheat doesn't edit items if you don't explicitly edit them so it's really worrying if this isn't really the case

if it's simply the case that starbound resets the gun on load if it doesn't like the combination of projectile stats, that's not so serious and can be worked around

**Comment by mouseas** [comment] 2015-05-28 21:42
@wizzomafizzo They're the same bug. Whether starcheat is incorrectly editing the gun or starbound is breaking the shotguns when it loads my character I'm not sure. I do know that every shotgun I've picked up in starbound during gameplay, then opened in starcheat comes back with 1 projectile instead of its original number of projectiles.

**Comment by mouseas** [comment] 2015-05-28 21:44
Does starcheat have a template JSON that it expects a gun to follow when it loads it, or does it just take whatever JSON is present?

**Comment by wizzomafizzo** [comment] 2015-05-29 02:17
here is the code that generates guns initially: https://github.com/wizzomafizzo/starcheat/blob/master/starcheat/assets/items.py#L215

it's pretty basic right now and just gets guns to a point that starbound accepts them as valid. i've made some updates to it last night which i haven't uploaded yet but it's essentially the same.

here is the code that actually triggers a new gun creation:
https://github.com/wizzomafizzo/starcheat/blob/master/starcheat/gui/itemedit.py#L270

you can see the only place it gets called is here, which itself is only triggered once you click ok on the item browser (overwriting the original item):
https://github.com/wizzomafizzo/starcheat/blob/master/starcheat/gui/itemedit.py#L408

aside from that, startcheat doesn't have any concept of projectilecount or any gun-specific attributes, and doesn't edit items by itself

**Comment by wizzomafizzo** [comment] 2015-05-29 02:20
if you have any example guns using multiple projectiles that i can test please upload them. i spent 3 hours last night finding guns on planets, came up with about 20 and every single one only used a single projectile, couldn't find any shotguns (made absolutely sure there was no nerfing going on by itself, guns were identical before and after being saved in starcheat)

**Comment by wizzomafizzo** [comment] 2015-05-30 05:56
Hi guys. Could you give the latest release (0.24) a crack and let me know if it's working now.

**Comment by wizzomafizzo** [comment] 2015-06-06 07:46
I'm sure this is fixed now so I'm gonna close this, please let me know if it's not working still and I'll reopen

**Closed by wizzomafizzo** 2015-06-06 07:46 UTC
Labels: bug, waiting
