### ISSUE TITLE
... Help me (Sorry,Russian version in this computer)

### ISSUE THREAD

**Issue by 555Alex555** [wizzomafizzo/starcheat#180] opened 2015-04-25 15:21 UTC
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 74, in <module>
  File "build\starcheat.py", line 71, in main
  File "build\gui\mainwindow.py", line 166, in __init__
  File "build\gui\mainwindow.py", line 480, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 76, in get_players
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:\\Starbound v Spirited_Girafe_I\\giraffe_storage\\player'

**Comment by wizzomafizzo** [comment] 2015-04-26 06:02
hi there. could you please run through these instructions so i can see a copy of the detailed starcheat log: https://github.com/wizzomafizzo/starcheat/wiki/help#how-to-get-logs

haven't seen this error in a while so interested to see what the problem is

**Comment by FanatiG** [comment] 2015-05-03 20:19
his game doesnt see "player" file in 'C:\Starbound v Spirited_Girafe_I\giraffe_storage\player' (if this info can help you)

**Comment by wizzomafizzo** [comment] 2015-05-06 14:59
Really need a copy of the log files to make any sense of it, sorry. It says where they are in the link

**Comment by wizzomafizzo** [comment] 2015-05-30 06:01
Try the latest release and see if that's fixed it. If not, let me know with a copy of your logs and I will reopen, but in the meantime I'm closing it cause I've got nothing to go on.

**Closed by wizzomafizzo** 2015-05-30 06:01 UTC
Labels: bug, waiting
