### ISSUE TITLE
Character's not showing up in character select screen after editing.

### ISSUE THREAD

**Issue by MavJones** [wizzomafizzo/starcheat#131] opened 2015-01-31 17:03 UTC
I've honestly no idea why this is happening. It should really be looked into. I've spent hours fiddling with characters to try and see what exactly is breaking, yet nothing seems to work.

**Comment by MavJones** [comment] 2015-01-31 17:06
https://www.dropbox.com/s/5s6z34rmb843rvr/45aa884e75375f4138f0349c58f771ad.player?dl=0

Link to my player file.

**Comment by chrmoritz** [comment] 2015-01-31 17:07
this is a duplicate of #124 
and don't worry, we are already looking into this issue

**Comment by chrmoritz** [comment] 2015-02-05 05:40
Could you please try [version 0.19](https://github.com/wizzomafizzo/starcheat/releases/tag/0.19) and report back if this has fixed your issue.

**Comment by Sonador** [comment] 2015-02-06 01:26
Character still does not show in menu.

**Comment by wizzomafizzo** [comment] 2015-02-10 17:00
@Sonador if you are having any bug besides some of the equipped techs not working could you please create a new issue ticket

**Closed** 2015-02-17 02:17 UTC
Labels: bug, duplicate
