### ISSUE TITLE
[Win 10] It is not working

### ISSUE THREAD

**Issue by id6016** [wizzomafizzo/starcheat#207] opened 2015-08-14 18:33 UTC
Starcheat is not even loading for me
Here's the image of the error
http://i.imgur.com/zrcwDPW.png

**Comment by wizzomafizzo** [comment] 2015-08-15 15:17
Has it ever worked for you or is this just happening with the latest version? What version of Windows are you running?

**Comment by Reedfish** [comment] 2015-11-13 22:50
hey, actualy found this thread im getting the same error, at first it was a ----100.dll file was missing after fixing that i started getting that error. im on windows ten and the latest verison.

the weird thing is on another PC with win-10 it was working fine

**Comment by chrmoritz** [comment] 2015-11-14 01:00
duplicate of #220 

Use the [latest starcheat version](https://github.com/wizzomafizzo/starcheat/releases), which is build against Windows 2015 to fix your issue

**Comment by Reedfish** [comment] 2015-11-14 01:08
its still the same error :c

**Comment by chrmoritz** [comment] 2015-11-14 01:16
What version of starcheat are you using (32 or 64 bit)?

Maybe the error is related to todays big win 10 update (1511). Do you have it installed? (I can't test it atm, because Microsoft doesn't like me and I'm still unable to download the update.)

**Comment by Reedfish** [comment] 2015-11-14 01:27
64bit, and im on a 64bit system
havent updated yet maybe that will fix it ?

**Comment by chrmoritz** [comment] 2015-11-14 01:29
Don't think so. I thought the update could break it.
Also I started a new test build with the latest stuff. You can [download it from here](https://ci.appveyor.com/api/buildjobs/ley6h6tb8pek5agd/artifacts/dist/starcheat--win64.zip).

**Comment by Reedfish** [comment] 2015-11-14 22:53
okay that seemed to do it, it must have auto updated :p 
test build works well though saving a char removes it from the selection tab, refresh fixes it

**Closed** 2015-12-18 03:20 UTC
Labels: bug
