### ISSUE TITLE
starcheat crash

### ISSUE THREAD

**Issue by Flagowy** [wizzomafizzo/starcheat#297] opened 2016-07-28 22:44 UTC
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 175, in __init__
  File "build\gui\mainwindow.py", line 554, in open_file
  File "build\gui\mainwindow.py", line 260, in update
  File "build\gui\mainwindow.py", line 718, in update_bag
  File "build\gui\common.py", line 116, in __init__
  File "build\gui\common.py", line 63, in inv_icon
  File "build\assets\items.py", line 141, in get_item_icon
AttributeError: 'list' object has no attribute 'split'

**Comment by Flagowy** [comment] 2016-07-28 23:02
And i have question - must have i Python on my computer? I don't have it.

**Comment by kurisubrooks** [comment] 2016-07-28 23:05
You don't require Python to be installed if using the prebuilt binaries. Python is only used for development. 

What nightly build version were you using? [Please update to the latest build](https://ci.appveyor.com/api/buildjobs/r9b5dcjujj6nibi6/artifacts/dist/starcheat-3191dea-win64.zip) and let us know if you still get this error.

**Comment by Flagowy** [comment] 2016-07-28 23:06
Thanks for your time. 

I will check your version. I tried on "starcheat-d44164e-win64".

**Comment by kurisubrooks** [comment] 2016-07-28 23:07
The latest nightly build is `starcheat-3191deaa`, so you're running an outdated client. Let me know how it goes with the updated build.

**Comment by Flagowy** [comment] 2016-07-28 23:08
It working, thank you guy. :)

**Comment by Flagowy** [comment] 2016-07-28 23:11
I can change my character but he disapeared from list. Could you help me?

**Comment by kurisubrooks** [comment] 2016-07-28 23:13
If your player no longer shows in the game, you've corrupted your character. Undo any changes you did in Starcheat, save and see if it reappears.

**Comment by Flagowy** [comment] 2016-07-28 23:15
Can i "repair" my character? I can't undo it.

**Comment by kurisubrooks** [comment] 2016-07-28 23:16
Unfortunately i'm unaware of any way to undo corruption if you're not longer able to undo it yourself. Could you please provide us with your .player file? I'll have one of the developers take a look.

**Comment by Flagowy** [comment] 2016-07-28 23:20
This is it?


[player.docx](https://github.com/wizzomafizzo/starcheat/files/389583/player.docx)

**Comment by Flagowy** [comment] 2016-07-28 23:24
Maybe in TXT is better for you.
[player.txt](https://github.com/wizzomafizzo/starcheat/files/389588/player.txt)

**Comment by Flagowy** [comment] 2016-07-28 23:26
Sorry, wait. I do something wrong. Now it will be okay.
[player.txt](https://github.com/wizzomafizzo/starcheat/files/389596/player.txt)

**Comment by kurisubrooks** [comment] 2016-07-28 23:29
The file is in `Starbound/storage/players`, the file will be `{UUID}.player`. It must be in the format of `(random numbers).player`

**Comment by Flagowy** [comment] 2016-07-28 23:29
I give it in txt. I can't upload original file on this page.

**Comment by kurisubrooks** [comment] 2016-07-28 23:31
Alright, we'll try out best to find out what's going on here. It might take some time.

**Comment by Flagowy** [comment] 2016-07-28 23:32
Okay. Thanks you so much.

**Comment by Flagowy** [comment] 2016-07-28 23:34
If you help it - i will close game using alt+f4 and after that i didin't come before using Starcheat. Maybe this problem was earlier.

**Comment by Flagowy** [comment] 2016-07-28 23:42
Maybe i know what happened. I use cheat engine to froze timbers which i use and then when i use Starcheat i take this timbers to transh. This is possible that corrupted my character?

**Comment by kurisubrooks** [comment] 2016-07-28 23:44
Doing anything that the game isn't intended to do will generally cause you to break something in the progress. So this is likely the main cause.

**Comment by kurisubrooks** [comment] 2016-07-28 23:45
As this problem doesn't seem related to Starcheat, I think you can close the issue now.

**Comment by Flagowy** [comment] 2016-07-29 08:44
So you wont't check my character?

**Comment by kurisubrooks** [comment] 2016-07-29 08:46
I asked one of the developers but I think they must have forgot. They're
asleep currently but I'll nudge them again when they wake up, if I don't
forget...

**Comment by Flagowy** [comment] 2016-07-29 08:48
Okay I will be waiting for your answer. Anyway thanks you for help.

**Comment by Flagowy** [comment] 2016-07-29 10:11
https://www.reddit.com/r/starbound/comments/3yatma/how_do_i_fix_a_corrupted_character/

I found this but when i change my .player with .bak1-3 nothing change.

**Comment by kurisubrooks** [comment] 2016-07-29 10:12
If your player backups are corrupted, the corruption occurred before
starcheat. :/

You say you used a cheat engine to do something with logs? What do you mean
by this?

**Comment by Flagowy** [comment] 2016-07-29 10:20
It is possible that all my 3 backups are corrupted? All have other sizes. Maybe i do something wrong?

I'm lazy man and i must finish my wall so i froze my timbers to do it. When i left game and later use Starcheat and try to play, my character disapeared.

**Comment by Flagowy** [comment] 2016-07-29 10:21
When i replace my char with bak1 i must change type of this file or what? My character is in "player" and bak1 in "bak1".

**Comment by kurisubrooks** [comment] 2016-07-29 10:21
The game itself creates these backup files. If this happened while you were
using modded assets, then the problem is unrelated to starcheat.

**Comment by kurisubrooks** [comment] 2016-07-29 10:22
Replace .player.bak1 with .player

**Comment by Flagowy** [comment] 2016-07-29 10:23
Only delete .player and delete "bak1" from .player.bak1 or change the content?

**Comment by kurisubrooks** [comment] 2016-07-29 10:23
Just the file name.

**Comment by Flagowy** [comment] 2016-07-29 10:25
So... just delete ".player" from bak1 and nothing much? Other format do not mind? Sorry for stupid questions.

**Comment by kurisubrooks** [comment] 2016-07-29 10:26
No!!! Delete the .bak1 from the file name!!!!

**Comment by Flagowy** [comment] 2016-07-29 10:27
How can i do it? My name of this file is only: 9bd6c8dd0778931154bbb42adc2ee9f7.player (THIS IS BAK1).

**Comment by kurisubrooks** [comment] 2016-07-29 10:28
If you've already removed .bak1, so the file is valid. If it's still not
appearing in game, the backups are also corrupt.

**Comment by Flagowy** [comment] 2016-07-29 10:38
I really don't know how i can change file format.

**Comment by kurisubrooks** [comment] 2016-07-29 10:39
You already have. Your player file, and your backups are all corrupt. There
is nothing more you can do.

**Comment by Flagowy** [comment] 2016-07-29 10:39
![aaaaaaaaaa](https://cloud.githubusercontent.com/assets/20713194/17245979/7e7f6562-5589-11e6-8d9c-35b8be231b4b.png)

**Comment by Flagowy** [comment] 2016-07-29 10:39
I don't change anything.

**Comment by Flagowy** [comment] 2016-07-29 10:44
After some tries i did it. Thanks you so much Kurisu. I just must change in folder option to show file formats.

**Comment by wizzomafizzo** [comment] 2016-07-29 10:46
Dude, you rename the file "<random numbers>.player.bak1" to "<random numbers>.player" there's no trick or anything. 

If that does not fix it then there's not much you can do sorry. If all 3 backups are also corrupt it is likely nothing to do with starcheat but see how you go. I'd suggest being more careful with cheat engine in the future either way

**Comment by wizzomafizzo** [comment] 2016-07-29 10:47
Hah took too long to reply. Glad to hear it's working for you now

**Comment by Flagowy** [comment] 2016-07-29 10:53
I know, i use this really for this one time. Anyway - thanks you all for help. I lost just few missions but other is okay.

**Comment by kurisubrooks** [comment] 2016-07-29 11:37
@wizzomafizzo Can we please close this issue?

**Comment by wizzomafizzo** [comment] 2016-07-29 11:39
Sure

**Closed by wizzomafizzo** 2016-07-29 11:39 UTC
Labels: bug

**Comment by Flagowy** [comment] 2016-07-29 12:05
Haha sory guys but i have last question. Can i do somethink with cloned crew members?
