### ISSUE TITLE
better startup dialogs

### ISSUE THREAD

**Issue by chrmoritz** [wizzomafizzo/starcheat#161] opened 2015-02-17 02:32 UTC
* [ ] startup dialogs (pre mainWindow) doesn't have a task bar icon on windows and can easily get lost behind other windows
* [ ] starup dialogs (pre mainWindow) sometimes freeze the app on OS X

**Comment by wizzomafizzo** [comment] 2015-02-17 03:13
I think this is entirely caused by the dialogs being modal while the mainwindow has not been shown yet

Perhaps we can set the to non-modal (if that's possible) just during startup, but I assume that means they can't have a parent which ends up bad behaviour

We could also potentially change up the mainwindow so it's presentable even without any assets indexed and fields pre-filled, then we could show it before any of the setup dialogs appear

**Comment by chrmoritz** [comment] 2015-02-17 03:23
The modal setting should fixed the 2nd issue, but I don't think that it will change anything for the first issue. BTW: The pre mainWindow freeze on OS X is a PyQt only issue. PySide forms fine for me.

**Comment by chrmoritz** [comment] 2015-02-17 11:57
Changing the WindowModality of the QMessageBox to Qt.WindowModal fixed the issue on OS X and renders the modal as an OS X Sheet attached to an empty mainwindow (it changes nothing on windows):
![bildschirmfoto 2015-02-17 um 12 53 39](https://cloud.githubusercontent.com/assets/1686759/6227789/71d2afb6-b6a4-11e4-99b3-78e3e27baaf4.png)

**Comment by wizzomafizzo** [comment] 2015-02-17 12:30
did this fix both issues? (ignoring the blank screen)

if it did then we should be able to close this whole bug off if i just make sure the mainwindow looks ok empty, when we can show it earlier on so there's no white screen

i would like to make most of the dialogs windowmodal anyway, i think that flip down effect is pretty appropriate for the majority

**Comment by chrmoritz** [comment] 2015-02-18 01:08
Sheets are only available in aqua. There is nothing like this on windows, so this has no affect for the windows issue.

**Comment by wizzomafizzo** [comment] 2015-02-18 01:30
don't worry, that's what i mean. i was playing around with it on my mac earlier. i think showing the windows earlier in the process should fix the windows issue as well anyway

**Comment by wizzomafizzo** [comment] 2015-02-20 18:55
@chrmoritz when you've got a chance can you have another play with this using the latest commit it did

i rearranged everything so the show() is much sooner

it looks good except for one thing, the update_check seems to freeze the window during the check and make it white. no issues when updates are disabled. i put the update_check before show as a workaround for now but i'm guessing that still won't look good on mac?

**Comment by chrmoritz** [comment] 2015-02-20 20:03
I got a reverse behavior on OS X. Update check freezes when put before mainWindow.show but no issues when but after. Could you pls try it again with the new WindowModality?

**Comment by chrmoritz** [comment] 2015-02-20 20:27
the update check is now multi threaded, so I don't want to hear any complains about the web request adding half a second startup time anymore. 
BTW: one more reason I don't like urllib: no async webrequest

**Closed** 2015-02-20 20:40 UTC
Labels: enhancement

**Comment by wizzomafizzo** [comment] 2015-02-21 03:10
in case you're still wondering, (foo,) to create a single item tuple. i have to do the same shit with sqlite lib

**Comment by chrmoritz** [comment] 2015-02-21 11:16
@wizzomafizzo: I see the problem more withing the threading module. The doc says that it only takes a tuple as an argument, but if it's implementation sees an array it thinks: maybe some newbie could have mixed up tuples with array so lets interprets it as a tuple instead of handling it as a 1 element tuple with only an array as it's argument.

**Comment by wizzomafizzo** [comment] 2015-02-21 12:07
ahhhh ok i see. well that's stupid isn't it haha
