### ISSUE TITLE
Starbound - Unstable [Nightly] found bug when trying to load assets.

### ISSUE THREAD

**Issue by thakyZ** [wizzomafizzo/starcheat#279] opened 2016-05-01 15:20 UTC
## Issue details:
*Please try to fill out as many fields as you can below (by replacing the text between the two *).*

* starcheat version: *0.27.1*
* starbound version and branch (stable / unstable / nightly): *nightly*
* the error message your a getting if any:    
*I am getting no error message other than the default one.*    
* Insert error message from the details field of the error dialog here    
```Traceback (most recent call last):```   
```  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>```   
```  File "build\starcheat.py", line 83, in <module>```   
```  File "build\starcheat.py", line 80, in main```   
```  File "build\gui\mainwindow.py", line 154, in __init__```   
```  File "build\gui\utils.py", line 103, in check_index_valid```   
```  File "build\gui\utils.py", line 64, in build_assets_db```   
```  File "build\assets\core.py", line 127, in find_assets```   
```  File "build\assets\core.py", line 156, in scan_asset_folder```   
```  File "build\starbound\helpers.py", line 213, in open```   
```  File "build\starbound\helpers.py", line 220, in read_stream```   
```  File "build\starbound\btreedb4.py", line 119, in initialize```   
```  File "build\starbound\sbbf02.py", line 89, in initialize```   
```AssertionError: Invalid file format```   
* a link to your starcheat log file: *https://gist.github.com/thakyZ/4f19f73604efebbda5bee5f3f577101e*
* if the issue is related to a player files please upload the affected player file somewhere if possible: *[bf5afb1acb02e5121886ae553d6fcf1e.zip](https://github.com/wizzomafizzo/starcheat/files/244186/bf5afb1acb02e5121886ae553d6fcf1e.zip)*
* if the issue is related to a mod please link to the mod you are using if possible: *No mods*    
* Other notes:    
 * I attached the player file since the player file is possibly in a new version. I am only creating this issue because I want to bring to light what is going to change in the update to Cheerful Giraffe
 * Also the mods folder is stored in the main directory instead of giraffe_storage, and the player files, universe files, logs, and starbound config are stored in a folder called storage in the main directory.

**Comment by chrmoritz** [comment] 2016-05-01 22:09
Duplicate of #274: Starbound changed their save file format again in nightly.  Closing this because it's already tracked in #274.

**Closed by chrmoritz** 2016-05-01 22:09 UTC
Labels: duplicate
