### ISSUE TITLE
StarCheat Crash

### ISSUE THREAD

**Issue by jjaegun** [wizzomafizzo/starcheat#255] opened 2016-01-10 07:45 UTC
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 176, in __init__
  File "build\gui\mainwindow.py", line 542, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 119, in get_players
  File "build\gui\openplayer.py", line 136, in populate
  File "build\saves.py", line 586, in get_play_time
KeyError: 'playTime'

**Comment by chrmoritz** [comment] 2016-01-19 09:53
Duplicate of #254.

Starbound Nightly has changed the player file format without increasing it's format version. The new format is incompatible with Glad Giraffe and the current Starcheat version, but it's not successfully ignored by Starcheat because it still has the same format version as Glad Giraffe. This issues is more an upstream issue from Starbound Nightly (but since it's a nightly such issues can be expected) and not an issue with Starcheat.

To fix this you have to temporary move all nightly characters out of your player folder.

**Closed by chrmoritz** 2016-01-19 09:53 UTC
Labels: duplicate
