### ISSUE TITLE
Error when i run

### ISSUE THREAD

**Issue by andrewvl2** [wizzomafizzo/starcheat#220] opened 2015-08-31 21:30 UTC
i have an error when i run starcheat:
File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py",
line 27, in <module>
     exec(code, m._dict_)
File "build\starcheat.py", line9, in<module>
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py" line2237 in_find_and_load
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py" line2236 in_find_and_load
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py" line1191 in_load_unlocked
File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py" line1161 in_load_backward_compatible
File"ExtensionLoader_PyQt5_QtWidgets.py", line 22, in <module>
File"ExtensionLoader_PyQt5_QtWidgets.py", line 14, in _ bootstrap _
ImportError: DLL load failed: The specified module could not be found.

**Comment by wizzomafizzo** [comment] 2015-09-01 02:33
which version of windows are you running?

**Comment by andrewvl2** [comment] 2015-09-01 13:42
windows 10

**Comment by chrmoritz** [comment] 2015-09-01 22:08
duplicate of #206 
Could you please try to run [this version](https://ci.appveyor.com/api/buildjobs/i5a1h80jecpgjblu/artifacts/dist/starcheat--win32.zip) which was build on a newer windows version.

**Comment by andrewvl2** [comment] 2015-09-04 14:35
@chrmoritz thank you it works :D. I am so happy

**Comment by chrmoritz** [comment] 2015-09-04 14:48
thx, I updated the build on the official release site with the updated Windows 10 compatible versions.

**Closed by chrmoritz** 2015-09-04 14:48 UTC
Labels: duplicate
