### ISSUE TITLE
Starcheat 0.24 (Again a 0.23 Error)

### ISSUE THREAD

**Issue by IsaiahJM97** [wizzomafizzo/starcheat#198] opened 2015-06-05 04:35 UTC
Hello everyone. This post is mainly for wizzo, but please, if you know how to help tell me. 
So, many of you may have heard of the starcheat 0.23 error where starcheat would basically crash upon loading. I got an email 6 days ago (I know, a bit late) saying this was fixed, & I saw there was a new version.I downloaded it. It showed the character menu then I decided to close it because I wanted to test it on an new character first. As I went to close it, there was an update for the Assets. I decided to hit no for now, then I made my second character and then when I opened starcheat I updated the assets.. Then It crashes AGAIN. I deleted the starcheat from my folders but when I downloaded it again, The same error was there.,. Please do fix this or tell me how I can revert my starcheat back to before I did the update... I really want to use this tool. [I haven't used starcheat in a LONG time ;( ]

**Comment by IsaiahJM97** [comment] 2015-06-05 04:39
This is  my error:


Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 180, in __init__
  File "build\gui\mainwindow.py", line 547, in open_file
  File "build\gui\openplayer.py", line 58, in __init__
  File "build\gui\openplayer.py", line 93, in get_players
  File "build\assets\species.py", line 390, in render_player
  File "build\assets\species.py", line 212, in render_part
  File "build\assets\images.py", line 27, in get_image
IndexError: list index out of range

**Comment by JimClonk** [comment] 2015-06-05 06:40
Try unequipping all armour from your characters. It seems to crash trying to render a preview for them.

**Comment by IsaiahJM97** [comment] 2015-06-05 17:03
Hmm, alright then, I tried that with no armor on. The only items I had on me was two techs, my Matter Manipulator & It worked! Coolio.. Thanks!

**Comment by IsaiahJM97** [comment] 2015-06-05 17:04
I don't want to close this if Wizzo has not had a chance to read it, but If no activity happens in the next 48 hours,. I will close it.

**Comment by wizzomafizzo** [comment] 2015-06-06 06:43
Hi. @JimClonk is correct this is just an issue with showing some armour in the preview. You don't need to close this until it's fixed properly if you still want to be notified.

**Comment by wizzomafizzo** [comment] 2015-06-06 08:52
Could you please confirm if the newest release (0.25) fixes this? I've added a workaround so it should no longer crash the whole app, it just ignore the item instead, but I'd still like to know which items don't show so I can eventually put in a real fix.

**Comment by JimClonk** [comment] 2015-06-06 21:00
Do all vanilla armours have both male and female graphics? If yes, then that might be something causing problems as some modded armours have graphics used by both genders.

**Closed** 2015-12-18 03:20 UTC
Labels: bug, waiting

**Comment by IsaiahJM97** [comment] 2015-12-24 02:30
Did you quit updating starcheat or is it still being updated?

**Comment by wizzomafizzo** [comment] 2016-01-03 12:18
@IsaiahJM97 sorry for the late reply. it's still being updated. have you tried the latest version of starcheat? i closed this because it hadn't gotten a response in a while. if the issue is still happening please let me know and i'm happy to reopen it

**Comment by IsaiahJM97** [comment] 2016-01-08 03:25
Thank you & it's quite alright. I need to get back into the game soon. I
will be sure to give you feedback when I do. Im currently awaiting a better
laptop/PC. Feel free to close this now.
