### ISSUE TITLE
Shotgun misses parameters for shot spread

### ISSUE THREAD

**Issue by Xirukai** [wizzomafizzo/starcheat#177] opened 2015-04-22 09:27 UTC
No spread is present after editing a shotgun. Reverts to a single bullet.

**Comment by wizzomafizzo** [comment] 2015-04-22 16:54
hi. could you paste an example json version of this item that's not working or at least the item's name/id. thanks

**Comment by Xirukai** [comment] 2015-04-22 18:57
It regards all randomgenerated shotguns, prior to opening any of the randomgenerated shotguns. They work as intended. But afterwards, they get a bug and then its poof! Gone spread functionality.

They also changed functionality regarding to accuracy. It is now a variable that is found in the generatedgun files. Alongside projectilecount and projectileseperation.

This is what is in the shotgun files, with variations based on gun type etc.

{
  "name" : "commonshotgun",
  "maxStack" : 1,
  "rarity" : "common",
  "tooltipKind" : "gun",
  "handPosition" : [5, 2],
  "firePosition" : [-1, 10],
  "baseDps" : [5, 6],
  "rateOfFire" : [0.5, 4],
  "hands" : [2, 2],
  "recoilTime" : 0.1,
  "projectileCount" : [5, 15],
  "inaccuracy" : 0.13,
  "weaponType" : "Shotgun",
  "multiplier" : 1.0,
  "muzzleFlashes" : [
    "/animations/muzzleflash/bulletmuzzle1/bulletmuzzle1.animation",
    "/animations/muzzleflash/bulletmuzzle2/bulletmuzzle2.animation",
    "/animations/muzzleflash/bulletmuzzle3/bulletmuzzle3.animation"
  ],
  "projectileTypes" : [ "bullet-1", "bullet-2", "bullet-3", "bullet-4", "pellet" ],
  "directories" : [ "/items/guns/randomgenerated/shotgun/" ],
  "fireSound" : [ "/sfx/gun/shotgun4.wav" ],
  "palette" : [
    { "e35f5d" : "aa1d1b", "b22042" : "8b1311", "871132" : "5d0100", "808080" : "808080", "606060" : "606060", "404040" : "404040" },
    { "e35f5d" : "64967f", "b22042" : "446556", "871132" : "1e2c26", "808080" : "787784", "606060" : "4f545a", "404040" : "33343c" },
    { "e35f5d" : "ff9d1e", "b22042" : "bb6a0b", "871132" : "6b3501", "808080" : "787784", "606060" : "4f545a", "404040" : "33343c" },
    { "e35f5d" : "787784", "b22042" : "4f545a", "871132" : "404040", "808080" : "808080", "606060" : "606060", "404040" : "404040" },
    { "e35f5d" : "cb13ff", "b22042" : "9b1dcf", "871132" : "580682", "808080" : "787784", "606060" : "4f545a", "404040" : "33343c" }
  ],
  "nameGenerator" : "shotgunnames.config:nameGen"
}


Exported JSON with the bug, altering anything will revert it back to the file it originates from. 

{
    "count": 1,
    "name": "generatedgun",
    "parameters": {
        "accuracy": null,
        "baseDps": [
            5,
            6
        ],
        "classMultiplier": 1,
        "directories": [
            "/items/guns/randomgenerated/shotgun/"
        ],
        "drawables": [
            {
                "image": "/items/guns/randomgenerated/shotgun/butt/17.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    -9.899999618530273,
                    0
                ]
            },
            {
                "image": "/items/guns/randomgenerated/shotgun/middle/18.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    0,
                    0
                ]
            },
            {
                "image": "/items/guns/randomgenerated/shotgun/barrel/9.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    12.899999618530273,
                    0
                ]
            }
        ],
        "firePosition": [
            19,
            2
        ],
        "fireSound": [
            "/sfx/gun/shotgun3.wav"
        ],
        "fireTime": 0.2613149881362915,
        "generated": true,
        "handPosition": [
            -5,
            -2
        ],
        "hands": [
            2,
            2
        ],
        "inaccuracy": 0.1,
        "inventoryIcon": [
            {
                "image": "/items/guns/randomgenerated/shotgun/butt/17.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    -9.899999618530273,
                    0
                ]
            },
            {
                "image": "/items/guns/randomgenerated/shotgun/middle/18.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    0,
                    0
                ]
            },
            {
                "image": "/items/guns/randomgenerated/shotgun/barrel/9.png?replace;404040=33343c;871132=6b3501;606060=4f545a;808080=787784;b22042=bb6a0b;e35f5d=ff9d1e",
                "position": [
                    12.899999618530273,
                    0
                ]
            }
        ],
        "itemName": "generatedgun",
        "level": 100,
        "levelScale": 385,
        "maxStack": 1,
        "multiplier": 1,
        "muzzleEffect": {
            "animation": "/animations/muzzleflash/bulletmuzzle3/bulletmuzzle3.animation",
            "fireSound": [
                {
                    "file": "/sfx/gun/shotgun3.wav"
                }
            ]
        },
        "muzzleFlashes": [
            "/animations/muzzleflash/bulletmuzzle1/bulletmuzzle1.animation",
            "/animations/muzzleflash/bulletmuzzle2/bulletmuzzle2.animation",
            "/animations/muzzleflash/bulletmuzzle3/bulletmuzzle3.animation"
        ],
        "name": "legendaryshotgun",
        "nameGenerator": "shotgunnames.config:nameGen",
        "palette": [
            {
                "404040": "404040",
                "606060": "606060",
                "808080": "808080",
                "871132": "5d0100",
                "b22042": "8b1311",
                "e35f5d": "aa1d1b"
            },
            {
                "404040": "33343c",
                "606060": "4f545a",
                "808080": "787784",
                "871132": "1e2c26",
                "b22042": "446556",
                "e35f5d": "64967f"
            },
            {
                "404040": "33343c",
                "606060": "4f545a",
                "808080": "787784",
                "871132": "6b3501",
                "b22042": "bb6a0b",
                "e35f5d": "ff9d1e"
            },
            {
                "404040": "404040",
                "606060": "606060",
                "808080": "808080",
                "871132": "404040",
                "b22042": "4f545a",
                "e35f5d": "787784"
            },
            {
                "404040": "33343c",
                "606060": "4f545a",
                "808080": "787784",
                "871132": "580682",
                "b22042": "9b1dcf",
                "e35f5d": "cb13ff"
            }
        ],
        "projectile": {
            "level": 100,
            "power": 0.2612612247467041
        },
        "projectileCount": 1,
        "projectileSeparation": 0,
        "projectileType": "explosivebullet",
        "projectileTypes": [
            "trishot",
            "stickybullet",
            "explosivebullet"
        ],
        "rarity": "Legendary",
        "rateOfFire": [
            0.5,
            4
        ],
        "recoilTime": 0.10000000149011612,
        "shortdescription": "Wicked Stormmaker",
        "spread": null,
        "tooltipKind": "gun",
        "twoHanded": true,
        "weaponType": "Shotgun"
    }
}

**Comment by Xirukai** [comment] 2015-04-25 08:05
Need any additional information?

**Comment by wizzomafizzo** [comment] 2015-04-25 08:34
i'm still not quite following what's happening. is one of these correct?
- when a new shotgun is generated it's missing keys for spread etc
- when an existing shotgun is opened it starcheat, the keys are removed like spread

**Comment by Xirukai** [comment] 2015-04-25 10:18
Yes.

Because they altered how accuracy and gun projectiles work now.

projectileCount is the replacer for how many bullets the gun will use.
projectileSeperation is how far the bullets will spread from each other. (Wider or tighter spread.)

Inaccuracy replaces accuracy. The lower this number, the better the accuracy.

**Comment by wizzomafizzo** [comment] 2015-04-25 10:20
which one? the first or second on my list?

**Comment by Xirukai** [comment] 2015-04-25 10:51
Both.
Because they reworked on how the keys worked.
Spread is not used anymore, neither is accuracy.

**Comment by Xirukai** [comment] 2015-04-25 17:19
I found a fix to atleast get multiple projectiles again but not on how to get them to spread more.
You need to type in the same value for **spread** and **projectileCount** each time when editing a shotgun item. Then it will stick.

I will post again when I discovered a solution on how to apply the spread we all know and love.

**Comment by Xirukai** [comment] 2015-04-25 17:31
Okay, what I figured out is on how spread now functions.

You will need to have the last two values set at the same rate.
Then the spread is somehow calculated by the game through inaccuracy, ranging beteem 0.15~ to 0.02~
Depending on which type etc.

**Comment by wizzomafizzo** [comment] 2015-04-26 06:03
aight i think i get what the issue is now, i will keep you up to date on the progress. thanks for your investigation to much appreciated

**Comment by Xirukai** [comment] 2015-04-26 08:21
Alright, let me know if I need to test it.

**Comment by wizzomafizzo** [comment] 2015-05-27 11:19
hey @Xirukai could i please get a little more info from you. i'm looking at doing a hotfix soon with this included with it

have you had any issues with starcheat automatically changing the spread on shotguns simply from loading and saving the player? i have another similar bug that came in where they say that is happening, but i'm trying to figure if it's actually the case or they just think starcheat is doing it while starbound is the culprit (ignoring that i still generate guns incorrectly initially)

**Comment by wizzomafizzo** [comment] 2015-05-30 06:00
Can you give the latest release a go (0.24) and let me know if it's working now. The issue was that I was writing items with the wrong item format version number, separate from the item itself, which was causing Starbound to "upgrade" them to the new version every load, resetting a few stats.

**Comment by wizzomafizzo** [comment] 2015-06-06 07:45
I'm sure this is fixed now so I'm gonna close this, please let me know if it's not working still and I'll reopen

**Closed by wizzomafizzo** 2015-06-06 07:45 UTC
Labels: bug, waiting
